# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bee4.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbee4.proto\".\n\rNodeCondition\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0c\n\x04idle\x18\x02 \x01(\x08\"F\n\x04\x46\x65\x65\x64\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0f\n\x07\x62otType\x18\x02 \x01(\t\x12\x0e\n\x06script\x18\x03 \x01(\t\x12\x11\n\tbotAnswer\x18\x04 \x01(\t\"\x0c\n\nEmptyParam2\x7f\n\x0b\x42\x65\x65\x34Service\x12,\n\rAreYouHealthy\x12\x0b.EmptyParam\x1a\x0e.NodeCondition\x12)\n\nAreYouIdle\x12\x0b.EmptyParam\x1a\x0e.NodeCondition\x12\x17\n\x07\x44\x65liver\x12\x05.Feed\x1a\x05.FeedB\x1f\n\x10net.kkennib.grpcB\tBee4ProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bee4_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020net.kkennib.grpcB\tBee4ProtoP\001'
  _globals['_NODECONDITION']._serialized_start=14
  _globals['_NODECONDITION']._serialized_end=60
  _globals['_FEED']._serialized_start=62
  _globals['_FEED']._serialized_end=132
  _globals['_EMPTYPARAM']._serialized_start=134
  _globals['_EMPTYPARAM']._serialized_end=146
  _globals['_BEE4SERVICE']._serialized_start=148
  _globals['_BEE4SERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
