# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorkProtocolService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19WorkProtocolService.proto\x12\x10net.kkennib.grpc\"\x95\x01\n\x04Work\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0f\n\x07groupNo\x18\x02 \x01(\x05\x12\x10\n\x08keywords\x18\x03 \x03(\t\x12\x10\n\x08\x63hannels\x18\x04 \x03(\t\x12\x17\n\x0f\x63ollectionDates\x18\x05 \x03(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t\x12\x13\n\x0brequestType\x18\x08 \x01(\t\"1\n\x05Works\x12(\n\x08workList\x18\x01 \x03(\x0b\x32\x16.net.kkennib.grpc.Work\".\n\x0cWorkResponse\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb1\x03\n\x13WorkProtocolService\x12\x38\n\x04\x65\x63ho\x12\x17.net.kkennib.grpc.Works\x1a\x17.net.kkennib.grpc.Works\x12\x46\n\x0b\x63ollectUrls\x12\x17.net.kkennib.grpc.Works\x1a\x1e.net.kkennib.grpc.WorkResponse\x12\x46\n\x0b\x63ollectDocs\x12\x17.net.kkennib.grpc.Works\x1a\x1e.net.kkennib.grpc.WorkResponse\x12G\n\x0c\x65xtractTexts\x12\x17.net.kkennib.grpc.Works\x1a\x1e.net.kkennib.grpc.WorkResponse\x12J\n\x0f\x65xtractContents\x12\x17.net.kkennib.grpc.Works\x1a\x1e.net.kkennib.grpc.WorkResponse\x12;\n\x07request\x12\x17.net.kkennib.grpc.Works\x1a\x17.net.kkennib.grpc.Worksb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WorkProtocolService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WORK']._serialized_start=48
  _globals['_WORK']._serialized_end=197
  _globals['_WORKS']._serialized_start=199
  _globals['_WORKS']._serialized_end=248
  _globals['_WORKRESPONSE']._serialized_start=250
  _globals['_WORKRESPONSE']._serialized_end=296
  _globals['_WORKPROTOCOLSERVICE']._serialized_start=299
  _globals['_WORKPROTOCOLSERVICE']._serialized_end=732
# @@protoc_insertion_point(module_scope)
