server:
  manager:
    addr: "localhost"
    port: 8084
  worker:
    addr: "localhost"
    port: 8085

storage:
  rdb:
    app:
      local:
        host: localhost
        port: 5432
        username: postgres
        password: 3968
        dbname: postgres
      rds:
        host: =====
        port: =====
        username: =====
        password: =====
        dbname: =====
  nosql:
    dynamo:
      remote:
        region: =====
        key:
          access: =====
          secret: =====

project:
  root: E:\gRPCSample