/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.kkennib.grpc;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        ApplicationContext context = SpringApplication.run(App.class, args);
        GrpcClientService grpcClientService = context.getBean(GrpcClientService.class);
        grpcClientService.areYouHealthy();
    }
}

